name: Morning Routine

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Morning Routine
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
  -d "chat_id=${CHAT_ID}" \
  --data-urlencode "text=GOOD MORNING"
